[package]
name = "ocelli-dicom"
description = "Parsing, transfer-syntax dispatch, metadata model and providers."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
