#!/usr/bin/env python3
"""Generate Codex repository skills from the canonical Claude workflow files.

One workflow, two hosts. `.claude/commands/*.md` and `.claude/skills/*/SKILL.md`
stay canonical. Codex discovers checked-in adapters under `.agents/skills/`.

An adapter does NOT duplicate its source. It names the canonical file, records
that file's SHA-256, and instructs the host to read it. Duplicating the body
would create two documents that drift, and a workflow whose two copies disagree
is worse than a workflow that only one host can run.

The recorded SHA is what makes drift detectable: `--check` recomputes it, so an
edited command with a stale adapter fails the gate rather than silently
serving Codex an out-of-date instruction.

Usage:
  python3 scripts/sync_agent_skills.py
  python3 scripts/sync_agent_skills.py --check
"""

from __future__ import annotations

import argparse
import hashlib
import re
import shutil
import sys
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
COMMANDS = ROOT / ".claude" / "commands"
SKILLS = ROOT / ".claude" / "skills"
OUT = ROOT / ".agents" / "skills"

GENERATED = "<!-- Generated by scripts/sync_agent_skills.py. Do not edit. -->"
NAME_RE = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")

BODY = """{generated}

Canonical source: `{source}`.

Source SHA-256: `{digest}`.

Before acting, read the canonical source completely and follow it using this
host's available tools. Treat invocation arguments as arguments to that
workflow.

A reference to another slash command means follow the corresponding repository
skill of the same name. A reference to `AskUserQuestion` means ask the operator
through this host's question mechanism. A reference to a subagent means use
this host's equivalent, or run the step inline if it has none.

Do not edit this generated adapter. Change the canonical source and run
`python3 scripts/sync_agent_skills.py`.
"""


@dataclass(frozen=True)
class Source:
    name: str
    description: str
    source: str
    digest: str
    invocable: bool


def split_frontmatter(text: str, path: Path) -> tuple[dict[str, str], str]:
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        raise ValueError(f"{path}: missing YAML frontmatter")
    try:
        end = lines[1:].index("---") + 1
    except ValueError as error:
        raise ValueError(f"{path}: unterminated frontmatter") from error

    meta: dict[str, str] = {}
    key = None
    for line in lines[1:end]:
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        if ":" in line and not line.startswith((" ", "\t")):
            key, value = line.split(":", 1)
            key = key.strip()
            meta[key] = value.strip().strip('"').strip("'")
        elif key is not None:
            # A folded continuation line, which long descriptions use.
            meta[key] = f"{meta[key]} {line.strip()}".strip()
    return meta, "\n".join(lines[end + 1:])


def load() -> list[Source]:
    found: list[Source] = []
    seen: set[str] = set()

    candidates: list[tuple[Path, bool]] = []
    candidates += [(p, True) for p in sorted(COMMANDS.glob("*.md"))]
    candidates += [(p, False) for p in sorted(SKILLS.glob("*/SKILL.md"))]

    for path, invocable in candidates:
        raw = path.read_bytes()
        meta, _ = split_frontmatter(raw.decode("utf-8"), path)

        name = meta.get("name") or path.stem
        if not invocable and path.name == "SKILL.md":
            name = meta.get("name") or path.parent.name
        if not NAME_RE.match(name):
            raise ValueError(f"{path}: name {name!r} is not kebab-case")
        if name in seen:
            raise ValueError(f"duplicate skill name {name!r} at {path}")
        seen.add(name)

        description = meta.get("description", "").strip()
        if not description:
            raise ValueError(f"{path}: frontmatter has no description")

        found.append(Source(
            name=name,
            description=description,
            source=path.relative_to(ROOT).as_posix(),
            digest=hashlib.sha256(raw).hexdigest(),
            invocable=invocable,
        ))
    return found


def render(item: Source) -> dict[str, str]:
    skill = (
        "---\n"
        f"name: {item.name}\n"
        f'description: "{item.description.replace(chr(34), chr(39))}"\n'
        "---\n\n"
        + BODY.format(generated=GENERATED, source=item.source,
                      digest=item.digest)
    )

    short = item.description
    if len(short) > 70:
        short = short[:67].rstrip() + "..."
    title = item.name.replace("-", " ").title()
    prompt = (f"Use ${item.name} to follow the repository workflow."
              if item.invocable else
              f"Load ${item.name} as reference material before acting.")

    agent = (
        "interface:\n"
        f'  display_name: "{title}"\n'
        f'  short_description: "{short.replace(chr(34), chr(39))}"\n'
        f'  default_prompt: "{prompt}"\n'
        "policy:\n"
        f"  allow_implicit_invocation: {str(not item.invocable).lower()}\n"
    )
    return {"SKILL.md": skill, "agents/openai.yaml": agent}


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    try:
        sources = load()
    except ValueError as error:
        print(f"FAIL: {error}")
        return 1

    expected: dict[str, str] = {}
    for item in sources:
        for relative, text in render(item).items():
            expected[f"{item.name}/{relative}"] = text

    if args.check:
        problems = []
        for relative, text in sorted(expected.items()):
            path = OUT / relative
            if not path.exists():
                problems.append(f"missing adapter {relative}")
            elif path.read_text() != text:
                problems.append(f"{relative} is stale, its source changed")
        existing = {
            p.relative_to(OUT).as_posix()
            for p in OUT.rglob("*") if p.is_file()
        } if OUT.is_dir() else set()
        for orphan in sorted(existing - set(expected)):
            problems.append(f"{orphan} has no canonical source")

        if problems:
            print("FAIL: Codex adapters are out of sync")
            for problem in problems:
                print(f"  {problem}")
            print("\nRun: python3 scripts/sync_agent_skills.py")
            return 1
        print(f"OK: {len(sources)} adapters match their canonical sources")
        return 0

    if OUT.is_dir():
        shutil.rmtree(OUT)
    for relative, text in expected.items():
        path = OUT / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)

    invocable = sum(1 for s in sources if s.invocable)
    print(f"wrote {len(sources)} adapters to .agents/skills/ "
          f"({invocable} commands, {len(sources) - invocable} skills)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
